apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: egaf51nue-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/egaf51nue-dotnet-basic-gitops